server {
    listen 1024;
	autoindex on;
    location / {
    }

    location /submit/ {
        client_max_body_size 20;
        index sentence.txt;
    }

    location /cgi-bin/ {
		index test.py;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /bin/bash;
        cgi_pass .pl /usr/bin/perl;
        cgi_pass .rb /usr/bin/ruby;
        cgi_pass .js /usr/bin/node;
        cgi_pass .php /usr/bin/php-cgi;
    }
}

server {
    listen 1025;
    location /white/ {
        methods GET;
        index index_white.html;
    }
    location /green/ {
        redirect /white/;
    }
    location /external/ {
        redirect http://google.com;
    }
}

server {
    listen 1026;
    root www/green;
    errors_root www/green;
    index index_green.html;
    location / {
    }
}

server {
	listen 1027;
	root www/eval;
	location / {
	}
}
