server {
    listen 8080;

    location / {
    }

    location /api {
        index api.html;
    }
}

server {
    listen 8081;

    location / {
    }
}

server {
    listen 8082;
    listen 8083;

    location /api {
    }
}
