name: Webserv CI/CD

# Trigger workflow
on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Test Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind siege

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Main Project
        run: make

      - name: Compile Unit Tests
        run: |
          cd tests
          make

      - name: Run Unit Tests
        run: |
          cd tests
          ./tester

      - name: Run Integration Test
        run: |
          # create dummy config
          echo "server {
          }" > default.conf

          # start server
          ./webserv default.conf & SERVER_PID=$!

          # setup-time
          sleep 1

          # curl-test
          RESPONSE=$(curl -s http://localhost:8080/)

          # shut-down server
          kill $SERVER_PID

          # check response
          if [[ "$RESPONSE" !=  *"Hello from epoll"* ]]; then
            echo "Intergration Test Failed: Unexpected response -> $RESPONSE"
            exit 1
          fi

          echo "Integration Test Passed!"

      - name: Run Siege Test with Valgrind
        run: |
          # start server using valgrind
          valgrind --leak-check=full --error-exitcode=1 ./webserv conf-files/webserv.conf & SERVER_PID=$!

          # setup-time
          sleep 2

          # siege-test
          siege -c10 -t10s http://localhost:8080/

          # shut-down server
          kill -SIGTERM $SERVER_PID

          # valgrind exit code
          wait $SERVER_PID
